root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  for-users/verifying-a-smart-contract/hardhat-verification-plugin: ./devs/verification/hardhat-verification-plugin/README.md
